// Generated by ts-to-zod
import { z } from 'zod'
import {
  type ResourceQuery,
  VulnerabilityStatus,
  VulnerabilityDismissalReason,
  ResourceTagProperties,
} from './../types/backend-types'

// TODO: Check if this (taken from resources.ts in ror repo) or from go doc is correct

export const vulnerabilityStatusSchema = z.nativeEnum(VulnerabilityStatus)

export const vulnerabilityDismissalReasonSchema = z.nativeEnum(VulnerabilityDismissalReason)

export const resourceTagPropertiesSchema = z.nativeEnum(ResourceTagProperties)

export const rorResourceOwnerReferenceSchema = z.object({
  scope: z.string(),
  subject: z.string(),
})

export const resourceVulnerabilityEventSpecSchema = z.object({
  owner: rorResourceOwnerReferenceSchema,
  message: z.string(),
})

export const resourceVirtualMachineOperatingSystemStatusSchema = z.object({
  id: z.string(),
  name: z.string(),
  family: z.string(),
  version: z.string(),
  hostName: z.string(),
  powerState: z.string(),
  toolVersion: z.string(),
  architecture: z.string(),
})

export const resourceVirtualMachineNetworkStatusSchema = z.object({
  id: z.string(),
  dns: z.string(),
  ipv4: z.string(),
  ipv6: z.string(),
  mask: z.string(),
  gateway: z.string(),
  mac: z.string(),
})

export const resourceVirtualMachineMemoryStatusSchema = z.object({
  unit: z.string(),
  usage: z.number(),
  sizeBytes: z.number(),
})

export const resourceVirtualMachineDiskStatusSchema = z.object({
  usageBytes: z.number(),
  isMounted: z.boolean(),
  id: z.string(),
  name: z.string(),
  type: z.string(),
  sizeBytes: z.number(),
})

export const resourceVirtualMachineStateSchema = z.object({
  state: z.string(),
  reason: z.string(),
  time: z.string(),
})

export const resourceVirtualMachineTagSchema = z.object({
  key: z.string(),
  value: z.string(),
  description: z.string(),
})

export const resourceVirtualMachineCpuStatusSchema = z.object({
  unit: z.string(),
  usage: z.number(),
  sockets: z.number(),
  coresPerSocket: z.number(),
})

export const timeSchema = z.object({})

export const resourceVirtualMachineMemorySpecSchema = z.object({
  sizeBytes: z.number(),
})

export const resourceVirtualMachineDiskSpecSchema = z.object({
  id: z.string(),
  name: z.string(),
  type: z.string(),
  sizeBytes: z.number(),
})

export const resourceVirtualMachineCpuSpecSchema = z.object({
  sockets: z.number(),
  coresPerSocket: z.number(),
})

export const resourceVirtualMachineSpecSchema = z.object({
  cpu: resourceVirtualMachineCpuSpecSchema,
  name: z.string(),
  disks: z.array(resourceVirtualMachineDiskSpecSchema),
  memory: resourceVirtualMachineMemorySpecSchema,
})

export const resourceVirtualMachineStatusSchema = z.object({
  lastUpdated: timeSchema,
  location: z.string(),
  cpu: resourceVirtualMachineCpuStatusSchema,
  tags: z.record(z.string(), resourceVirtualMachineTagSchema),
  state: resourceVirtualMachineStateSchema,
  disks: z.array(resourceVirtualMachineDiskStatusSchema),
  memory: resourceVirtualMachineMemoryStatusSchema,
  networks: z.array(resourceVirtualMachineNetworkStatusSchema),
  operatingSystem: resourceVirtualMachineOperatingSystemStatusSchema,
})

export const resourceVirtualMachineClassSpecHardwareInstanceStorageSchema = z.object({
  storageClass: z.string(),
})

export const resourceVirtualMachineClassSpecHardwareSchema = z.object({
  cpus: z.number(),
  instanceStorage: resourceVirtualMachineClassSpecHardwareInstanceStorageSchema,
})

export const resourceVirtualMachineClassSpecSchema = z.object({
  description: z.string(),
  hardware: resourceVirtualMachineClassSpecHardwareSchema,
})

export const resourceVirtualMachineClassSchema = z.object({
  spec: resourceVirtualMachineClassSpecSchema,
  status: z.record(z.string(), z.string()),
})

export const resourceTanzuKubernetesReleaseStatusConditionSchema = z.object({
  lastTransitionTime: z.string(),
  message: z.string(),
  reason: z.string(),
  severity: z.string(),
  status: z.string(),
  type: z.string(),
})

export const resourceTanzuKubernetesReleaseStatusSchema = z.object({
  conditions: z.array(resourceTanzuKubernetesReleaseStatusConditionSchema),
})

export const resourceTanzuKubernetesReleaseSpecNodeImageRefSchema = z.object({
  apiVersion: z.string(),
  fieldPath: z.string(),
  kind: z.string(),
  namespace: z.string(),
  uid: z.string(),
})

export const resourceTanzuKubernetesReleaseSpecImageSchema = z.object({
  name: z.string(),
  repository: z.string(),
  tag: z.string(),
})

export const resourceTanzuKubernetesReleaseSpecSchema = z.object({
  images: z.array(resourceTanzuKubernetesReleaseSpecImageSchema),
  kubernetesVersion: z.string(),
  nodeImageRef: resourceTanzuKubernetesReleaseSpecNodeImageRefSchema,
  repository: z.string(),
  version: z.string(),
})

export const resourceTanzuKubernetesReleaseSchema = z.object({
  spec: resourceTanzuKubernetesReleaseSpecSchema,
  status: resourceTanzuKubernetesReleaseStatusSchema,
})

export const resourceTanzuKubernetesClusterStatusConditionsSchema = z.object({
  lastTransitionTime: z.string(),
  message: z.string(),
  reason: z.string(),
  severity: z.string(),
  status: z.string(),
  type: z.string(),
})

export const resourceTanzuKubernetesClusterStatusAPIEndpointsSchema = z.object({
  host: z.string(),
  port: z.number(),
})

export const resourceTanzuKubernetesClusterStatusSchema = z.object({
  apiEndpoints: z.array(resourceTanzuKubernetesClusterStatusAPIEndpointsSchema),
  conditions: z.array(resourceTanzuKubernetesClusterStatusConditionsSchema),
  phase: z.string(),
  totalWorkerReplicas: z.number(),
  version: z.string(),
})

export const resourceTanzuKubernetesClusterSpecTopologyNodePoolsVolumesSchema = z.object({
  capasity: z.record(z.string(), z.string()),
  mountPath: z.string(),
  name: z.string(),
  storageClass: z.string(),
})

export const resourceTanzuKubernetesClusterSpecTopologyNodePoolsTkrReferenceSchema = z.object({
  fieldPath: z.string(),
  kind: z.string(),
  name: z.string(),
  namespace: z.string(),
  uid: z.string(),
})

export const resourceTanzuKubernetesClusterSpecTopologyNodePoolsTkrSchema = z.object({
  reference: resourceTanzuKubernetesClusterSpecTopologyNodePoolsTkrReferenceSchema,
})

export const resourceTanzuKubernetesClusterSpecTopologyNodePoolsTaintsSchema = z.object({
  effect: z.string(),
  key: z.string(),
  timeAdded: z.string(),
  value: z.string(),
})

export const resourceTanzuKubernetesClusterSpecTopologyNodePoolsSchema = z.object({
  failureDomain: z.string(),
  labels: z.record(z.string(), z.string()),
  name: z.string(),
  nodeDrainTimeout: z.string(),
  replicas: z.number(),
  storageClass: z.string(),
  taints: z.array(resourceTanzuKubernetesClusterSpecTopologyNodePoolsTaintsSchema),
  tkr: resourceTanzuKubernetesClusterSpecTopologyNodePoolsTkrSchema,
  vmClass: z.string(),
  volumes: z.array(resourceTanzuKubernetesClusterSpecTopologyNodePoolsVolumesSchema),
})

export const resourceTanzuKubernetesClusterSpecTopologyControlPlaneTkrReferenceSchema = z.object({
  name: z.string(),
  kind: z.string(),
  namespace: z.string(),
  uid: z.string(),
})

export const resourceTanzuKubernetesClusterSpecTopologyControlPlaneTkrSchema = z.object({
  reference: resourceTanzuKubernetesClusterSpecTopologyControlPlaneTkrReferenceSchema,
})

export const resourceTanzuKubernetesClusterSpecTopologyControlPlaneSchema = z.object({
  nodeDrainTimeout: z.string(),
  replicas: z.number(),
  storageClass: z.string(),
  tkr: resourceTanzuKubernetesClusterSpecTopologyControlPlaneTkrSchema,
  vmClass: z.string(),
})

export const resourceTanzuKubernetesClusterSpecTopologySchema = z.object({
  controlPlane: resourceTanzuKubernetesClusterSpecTopologyControlPlaneSchema,
  nodePools: z.array(resourceTanzuKubernetesClusterSpecTopologyNodePoolsSchema),
})

export const resourceTanzuKubernetesClusterSpecSettingsStorageSchema = z.object({
  classes: z.array(z.string()),
  defaultClass: z.string(),
})

export const resourceTanzuKubernetesClusterSpecSettingsNetworkTrustAdditionalTrustedCASchema = z.object({
  data: z.string(),
  name: z.string(),
})

export const resourceTanzuKubernetesClusterSpecSettingsNetworkTrustSchema = z.object({
  additionalTrustedCAs: z.array(resourceTanzuKubernetesClusterSpecSettingsNetworkTrustAdditionalTrustedCASchema),
})

export const resourceTanzuKubernetesClusterSpecSettingsNetworkServicesSchema = z.object({
  cidrBlocks: z.array(z.string()),
})

export const resourceTanzuKubernetesClusterSpecSettingsNetworkProxySchema = z.object({
  httpProxy: z.string(),
  httpsProxy: z.string(),
  noProxy: z.string(),
})

export const resourceTanzuKubernetesClusterSpecSettingsNetworkPodsSchema = z.object({
  cidrBlocks: z.array(z.string()),
})

export const resourceTanzuKubernetesClusterSpecSettingsNetworkCniSchema = z.object({
  name: z.string(),
})

export const resourceTanzuKubernetesClusterSpecSettingsNetworkSchema = z.object({
  cni: resourceTanzuKubernetesClusterSpecSettingsNetworkCniSchema,
  pods: resourceTanzuKubernetesClusterSpecSettingsNetworkPodsSchema,
  proxy: resourceTanzuKubernetesClusterSpecSettingsNetworkProxySchema,
  serviceDomain: z.string(),
  services: resourceTanzuKubernetesClusterSpecSettingsNetworkServicesSchema,
  trust: resourceTanzuKubernetesClusterSpecSettingsNetworkTrustSchema,
})

export const resourceTanzuKubernetesClusterSpecSettingsSchema = z.object({
  network: resourceTanzuKubernetesClusterSpecSettingsNetworkSchema,
  storage: resourceTanzuKubernetesClusterSpecSettingsStorageSchema,
})

export const resourceTanzuKubernetesClusterSpecDistributionSchema = z.object({
  fullVersion: z.string(),
  version: z.string(),
})

export const resourceTanuzKuberntesClusterSpecSchema = z.object({
  distribution: resourceTanzuKubernetesClusterSpecDistributionSchema,
  settings: resourceTanzuKubernetesClusterSpecSettingsSchema,
  topology: resourceTanzuKubernetesClusterSpecTopologySchema,
})

export const resourceTanzuKubernetesClusterSchema = z.object({
  spec: resourceTanuzKuberntesClusterSpecSchema,
  status: resourceTanzuKubernetesClusterStatusSchema.optional(),
})

export const resourceStorageClassSchema = z.object({
  allowVolumeExpansion: z.boolean(),
  provisioner: z.string(),
  reclaimPolicy: z.string(),
  volumeBindingMode: z.string(),
})

export const resourceStatefulSetStatusSchema = z.object({
  replicas: z.number(),
  availableReplicas: z.number(),
  currentReplicas: z.number(),
  readyReplicas: z.number(),
  updatedReplicas: z.number(),
})

export const resourceStatefulSetSchema = z.object({
  status: resourceStatefulSetStatusSchema,
})

export const resourceSlackMessageStatusSchema = z.object({
  result: z.number(),
  timestamp: timeSchema,
  error: z.any(),
})

export const resourceSlackMessageSpecSchema = z.object({
  channelId: z.string(),
  message: z.string(),
})

export const resourceSlackMessageSchema = z.object({
  spec: resourceSlackMessageSpecSchema,
  status: z.array(resourceSlackMessageStatusSchema),
})

export const intOrStringSchema = z.object({
  Type: z.number(),
  IntVal: z.number(),
  StrVal: z.string(),
})

export const resourceServicePortsSchema = z.object({
  appProtocol: z.string(),
  name: z.string(),
  port: z.number(),
  protocol: z.string(),
  targetPort: intOrStringSchema,
})

export const resourceServiceSpecSchema = z.object({
  type: z.string(),
  selector: z.record(z.string(), z.string()),
  ports: z.array(resourceServicePortsSchema),
  clusterIP: z.string(),
  clusterIPs: z.array(z.string()),
  externalIPs: z.array(z.string()).optional(),
  externalName: z.string().optional(),
  ipFamilies: z.array(z.string()),
  ipFamilyPolicy: z.string(),
  internalTrafficPolicy: z.string(),
  externalTrafficPolicy: z.string(),
})

export const resourceRouteSlackReceiverSchema = z.object({
  channelId: z.string(),
})

export const resourceRouteReceiverSchema = z.object({
  slack: z.array(resourceRouteSlackReceiverSchema),
})

export const resourceRouteMessageTypeSchema = z.object({
  apiVersion: z.string(),
  kind: z.string(),
})

export const resourceRouteSpecSchema = z.object({
  messageType: resourceRouteMessageTypeSchema,
  receivers: resourceRouteReceiverSchema,
})

export const resourceRouteSchema = z.object({
  spec: resourceRouteSpecSchema,
})

export const resourceReplicaSetStatusSchema = z.object({
  availableReplicas: z.number(),
  readyReplicas: z.number(),
  replicas: z.number(),
})

export const resourceReplicaSetSpecSelectorMatchExpressionsSchema = z.object({
  key: z.string(),
  operator: z.string(),
  values: z.array(z.string()),
})

export const resourceReplicaSetSpecSelectorSchema = z.object({
  matchExpressions: z.array(resourceReplicaSetSpecSelectorMatchExpressionsSchema),
  matchLabels: z.record(z.string(), z.string()),
})

export const resourceReplicaSetSpecSchema = z.object({
  replicas: z.number(),
  selector: resourceReplicaSetSpecSelectorSchema,
})

export const resourceReplicaSetSchema = z.object({
  spec: resourceReplicaSetSpecSchema,
  status: resourceReplicaSetStatusSchema,
})

export const resourceProjectSpecRoleSchema = z.object({
  upn: z.string(),
  name: z.string(),
  role: z.string(),
  email: z.string(),
  phone: z.string(),
})

export const resourceProjectSpecSchema = z.object({
  projectName: z.string(),
  description: z.string(),
  active: z.boolean(),
  createdTime: z.string(),
  updatedTime: z.string(),
  roles: z.array(resourceProjectSpecRoleSchema),
  workorder: z.string(),
  serviceTag: z.string(),
  tags: z.array(z.string()),
})

export const resourceProjectSchema = z.object({
  spec: resourceProjectSpecSchema,
})

export const resourcePolicyReportSummarySchema = z.object({
  error: z.number(),
  fail: z.number(),
  pass: z.number(),
  skip: z.number(),
  warn: z.number(),
})

export const resourcePolicyReportResultsResourcesSchema = z.object({
  uid: z.string(),
  apiVersion: z.string(),
  kind: z.string(),
  name: z.string(),
})

export const resourcePolicyReportResultsSchema = z.object({
  policy: z.string(),
  message: z.string(),
  category: z.string(),
  properties: z.record(z.string(), z.string()),
  severity: z.string(),
  result: z.string(),
  resources: z.array(resourcePolicyReportResultsResourcesSchema),
})

export const resourcePolicyReportSchema = z.object({
  results: z.array(resourcePolicyReportResultsSchema),
  summary: resourcePolicyReportSummarySchema,
  lastReported: z.string().optional(),
})

export const resourcePodStatusSchema = z.object({
  message: z.string().optional(),
  phase: z.string().optional(),
  reason: z.string().optional(),
  startTime: z.string().optional(),
})

export const resourcePodSpecContainersPortsSchema = z.object({
  name: z.string().optional(),
  containerPort: z.number().optional(),
  protocol: z.string().optional(),
})

export const resourcePodSpecContainersSchema = z.object({
  name: z.string().optional(),
  image: z.string().optional(),
  ports: z.array(resourcePodSpecContainersPortsSchema).optional(),
})

export const resourcePodSpecSchema = z.object({
  containers: z.array(resourcePodSpecContainersSchema).optional(),
  serviceAccountName: z.string().optional(),
  nodeName: z.string().optional(),
})

export const resourcePodSchema = z.object({
  spec: resourcePodSpecSchema.optional(),
  status: resourcePodStatusSchema.optional(),
})

export const resourcePersistentVolumeClaimStatusSchema = z.object({
  accessModes: z.array(z.string()),
  capacity: z.record(z.string(), z.string()),
  phase: z.string(),
})

export const resourcePersistentVolumeClaimSpecResourcesSchema = z.object({
  limits: z.record(z.string(), z.string()).optional(),
  requests: z.record(z.string(), z.string()),
})

export const resourcePersistentVolumeClaimSpecSchema = z.object({
  accessModes: z.array(z.string()),
  resources: resourcePersistentVolumeClaimSpecResourcesSchema,
  storageClassName: z.string(),
  volumeMode: z.string(),
  volumeName: z.string(),
})

export const resourcePersistentVolumeClaimSchema = z.object({
  spec: resourcePersistentVolumeClaimSpecSchema,
  status: resourcePersistentVolumeClaimStatusSchema,
})

export const resourceNodeStatusNodeinfoSchema = z.object({
  architecture: z.string(),
  bootID: z.string(),
  containerRuntimeVersion: z.string(),
  kernelVersion: z.string(),
  kubeProxyVersion: z.string(),
  kubeletVersion: z.string(),
  machineID: z.string(),
  operatingSystem: z.string(),
  osImage: z.string(),
  systemUUID: z.string(),
})

export const resourceNodeStatusConditionsSchema = z.object({
  lastHeartbeatTime: z.string(),
  lastTransitionTime: z.string(),
  message: z.string(),
  reason: z.string(),
  status: z.string(),
  type: z.string(),
})

export const resourceNodeStatusCapacitySchema = z.object({
  cpu: z.string(),
  ephemeralStorage: z.string(),
  memory: z.string(),
  pods: z.string(),
})

export const resourceNodeStatusAddressesSchema = z.object({
  address: z.string(),
  type: z.string(),
})

export const resourceNodeStatusSchema = z.object({
  addresses: z.array(resourceNodeStatusAddressesSchema),
  capacity: resourceNodeStatusCapacitySchema,
  conditions: z.array(resourceNodeStatusConditionsSchema),
  nodeInfo: resourceNodeStatusNodeinfoSchema,
})

export const resourceNodeSpecTaintsSchema = z.object({
  effect: z.string(),
  key: z.string(),
})

export const resourceNodeSpecSchema = z.object({
  podCIDR: z.string().optional(),
  podCIDRs: z.array(z.string()).optional(),
  providerID: z.string().optional(),
  taints: z.array(resourceNodeSpecTaintsSchema).optional(),
})

export const resourceNodeSchema = z.object({
  spec: resourceNodeSpecSchema,
  status: resourceNodeStatusSchema,
})

export const resourceNetworkPolicyConditionSchema = z.object({
  lastTransitionTime: z.string(),
  message: z.string(),
  observedGeneration: z.number(),
  reason: z.string(),
  status: z.string(),
  type: z.string(),
})

export const resourceNetworkPolicyStatusSchema = z.object({
  conditions: z.array(resourceNetworkPolicyConditionSchema),
})

export const resourceNetworkPolicyPodSelectorSchema = z.object({
  matchLabels: z.record(z.string(), z.string()),
})

export const resourceNetworkPolicyPortSchema = z.object({
  endPort: z.number(),
  port: intOrStringSchema,
  protocol: z.string(),
})

export const resourceNetworkPolicySelectorExpressionSchema = z.object({
  key: z.string(),
  operator: z.string(),
  values: z.array(z.string()),
})

export const resourceNetworkPolicySelectorSchema = z.object({
  matchExpressions: z.array(resourceNetworkPolicySelectorExpressionSchema),
  matchLabels: z.record(z.string(), z.string()),
})

export const resourceNetworkPolicyIpBlockSchema = z.object({
  cidr: z.string(),
  except: z.array(z.string()),
})

export const resourceNetworkPolicyPeerSchema = z.object({
  ipBlock: resourceNetworkPolicyIpBlockSchema.optional(),
  namespaceSelector: resourceNetworkPolicySelectorSchema.optional(),
  podSelector: resourceNetworkPolicySelectorSchema.optional(),
})

export const resourceNetworkPolicyEgressRuleSchema = z.object({
  ports: z.array(resourceNetworkPolicyPortSchema),
  to: z.array(resourceNetworkPolicyPeerSchema),
})

export const resourceNetworkPolicyIngressRuleSchema = z.object({
  from: z.array(resourceNetworkPolicyPeerSchema),
  ports: z.array(resourceNetworkPolicyPortSchema),
})

export const resourceNetworkPolicySpecSchema = z.object({
  egress: z.array(resourceNetworkPolicyEgressRuleSchema),
  ingress: z.array(resourceNetworkPolicyIngressRuleSchema),
  podSelector: resourceNetworkPolicyPodSelectorSchema,
  policyTypes: z.array(z.string()),
})

export const resourceNamespaceSchema = z.object({})

export const kubernetesClusterConditionSchema = z.object({
  type: z.string(),
  status: z.string(),
  lastTransitionTime: z.string(),
  reason: z.string(),
  message: z.string(),
})

export const kubernetesClusterVersionSchema = z.object({
  name: z.string(),
  version: z.string(),
  branch: z.string(),
})

export const kubernetesClusterAutoscalingConfigSchema = z.object({
  enabled: z.boolean(),
  minReplicas: z.number(),
  maxReplicas: z.number(),
})

export const kubernetesClusterStatusPriceSchema = z.object({
  monthly: z.number(),
  yearly: z.number(),
})

export const quantitySchema = z.object({
  Format: z.string(),
})

export const kubernetesClusterStatusClusterStatusResourceSchema = z.object({
  capacity: quantitySchema,
  used: quantitySchema,
  percentage: z.number(),
})

export const kubernetesClusterStatusClusterStatusResourcesSchema = z.object({
  cpu: kubernetesClusterStatusClusterStatusResourceSchema,
  memory: kubernetesClusterStatusClusterStatusResourceSchema,
  gpu: kubernetesClusterStatusClusterStatusResourceSchema,
  disk: kubernetesClusterStatusClusterStatusResourceSchema,
})

export const kubernetesClusterControlPlaneStatusSchema = z.object({
  status: z.string(),
  message: z.string(),
  scale: z.number(),
  machineClass: z.string(),
  resources: kubernetesClusterStatusClusterStatusResourcesSchema,
})

export const kubernetesClusterNodePoolStatusSchema = z.object({
  name: z.string(),
  status: z.string(),
  message: z.string(),
  scale: z.number(),
  machineClass: z.string(),
  autoscaling: kubernetesClusterAutoscalingConfigSchema,
  resources: kubernetesClusterStatusClusterStatusResourcesSchema,
})

export const kubernetesClusterClusterDetailsSchema = z.object({
  externalId: z.string(),
  resources: kubernetesClusterStatusClusterStatusResourcesSchema,
  price: kubernetesClusterStatusPriceSchema,
  controlplane: kubernetesClusterControlPlaneStatusSchema,
  nodepools: z.array(kubernetesClusterNodePoolStatusSchema),
})

export const kubernetesClusterClusterStateSchema = z.object({
  cluster: kubernetesClusterClusterDetailsSchema,
  versions: z.array(kubernetesClusterVersionSchema),
  controlplaneendpoint: z.string(),
  egressIP: z.string(),
  lastUpdated: timeSchema,
  lastUpdatedBy: z.string(),
  created: timeSchema,
})

export const kubernetesClusterAutoscalingSpecSchema = z.object({
  enabled: z.boolean(),
  minReplicas: z.number(),
  maxReplicas: z.number(),
  scalingRules: z.array(z.string()),
})

export const kubernetesClusterSpecMetadataDetailsSchema = z.object({
  labels: z.record(z.string(), z.string()),
  annotations: z.record(z.string(), z.string()),
})

export const kubernetesClusterNodePoolSchema = z.object({
  machineClass: z.string(),
  provider: z.string(),
  name: z.string(),
  replicas: z.number(),
  autoscaling: kubernetesClusterAutoscalingSpecSchema,
  metadata: kubernetesClusterSpecMetadataDetailsSchema,
})

export const kubernetesClusterStorageSchema = z.object({
  class: z.string(),
  path: z.string(),
  size: z.string(),
})

export const kubernetesClusterSpecControlPlaneSchema = z.object({
  replicas: z.number(),
  provider: z.string(),
  machineClass: z.string(),
  metadata: kubernetesClusterSpecMetadataDetailsSchema,
  storage: z.array(kubernetesClusterStorageSchema),
})

export const kubernetesClusterWorkersSchema = z.object({
  nodePools: z.array(kubernetesClusterNodePoolSchema),
})

export const kubernetesClusterSpecDataSchema = z.object({
  clusterId: z.string(),
  provider: z.string(),
  datacenter: z.string(),
  region: z.string(),
  zone: z.string(),
  project: z.string(),
  workspace: z.string(),
  workorder: z.string(),
  environment: z.string(),
})

export const kubernetesClusterSpecTopologySchema = z.object({
  version: z.string(),
  controlplane: kubernetesClusterSpecControlPlaneSchema,
  workers: kubernetesClusterWorkersSchema,
})

export const kubernetesClusterSpecSchema = z.object({
  data: kubernetesClusterSpecDataSchema.optional(),
  topology: kubernetesClusterSpecTopologySchema.optional(),
})

export const kubernetesClusterStatusSchema = z.object({
  state: kubernetesClusterClusterStateSchema,
  phase: z.string(),
  conditions: z.array(kubernetesClusterConditionSchema),
})

export const resourceIngressStatusLoadBalancerIngressSchema = z.object({
  hostname: z.string(),
  ip: z.string(),
})

export const resourceIngressStatusLoadBalancerSchema = z.object({
  ingress: z.array(resourceIngressStatusLoadBalancerIngressSchema),
})

export const resourceIngressStatusSchema = z.object({
  loadBalancer: resourceIngressStatusLoadBalancerSchema,
})

export const resourceIngressSpecTlsSchema = z.object({
  hosts: z.array(z.string()),
  secretName: z.string(),
})

export const resourceIngressSpecBackendServicePortSchema = z.object({
  name: z.string().optional(),
  number: z.number().optional(),
})

export const resourceIngressSpecBackendServiceSchema = z.object({
  name: z.string().optional(),
  port: resourceIngressSpecBackendServicePortSchema.optional(),
})

export const resourceIngressSpecBackendResourceSchema = z.object({
  apiGroup: z.string().optional(),
  kind: z.string().optional(),
  name: z.string().optional(),
})

export const resourceIngressSpecRulesHttpPathsBackendSchema = z.object({
  resource: resourceIngressSpecBackendResourceSchema.optional(),
  service: resourceIngressSpecBackendServiceSchema.optional(),
})

export const resourceIngressClassSpecParametersSchema = z.object({
  apiGroup: z.string(),
  kind: z.string(),
  name: z.string(),
  namespace: z.string(),
  scope: z.string(),
})

export const resourceIngressClassSpecSchema = z.object({
  controller: z.string(),
  parameters: resourceIngressClassSpecParametersSchema,
})

export const resourceIngressClassSchema = z.object({
  spec: resourceIngressClassSpecSchema,
})

export const resourceEndpointSpecSubsetsPortsSchema = z.object({
  appProtocol: z.string().optional(),
  name: z.string().optional(),
  port: z.number().optional(),
  protocol: z.string().optional(),
})

export const resourceEndpointSpecSubsetsNotReadyAddressesTargetRefSchema = z.object({
  apiVersion: z.string().optional(),
  fieldPath: z.string().optional(),
  kind: z.string().optional(),
  name: z.string().optional(),
  namespace: z.string().optional(),
  resourceVersion: z.string().optional(),
  uid: z.string().optional(),
})

export const resourceEndpointSpecSubsetsNotReadyAddressesSchema = z.object({
  hostname: z.string().optional(),
  ip: z.string().optional(),
  nodeName: z.string().optional(),
  targetRef: resourceEndpointSpecSubsetsNotReadyAddressesTargetRefSchema.optional(),
})

export const resourceEndpointSpecSubsetsAddressesTargetRefSchema = z.object({
  apiVersion: z.string().optional(),
  fieldPath: z.string().optional(),
  kind: z.string().optional(),
  name: z.string().optional(),
  namespace: z.string().optional(),
  resourceVersion: z.string().optional(),
  uid: z.string().optional(),
})

export const resourceEndpointSpecSubsetsAddressesSchema = z.object({
  hostname: z.string().optional(),
  ip: z.string().optional(),
  nodeName: z.string().optional(),
  targetRef: resourceEndpointSpecSubsetsAddressesTargetRefSchema.optional(),
})

export const resourceEndpointSpecSubsetsSchema = z.object({
  addresses: z.array(resourceEndpointSpecSubsetsAddressesSchema).optional(),
  notReadyAddresses: z.array(resourceEndpointSpecSubsetsNotReadyAddressesSchema).optional(),
  ports: z.array(resourceEndpointSpecSubsetsPortsSchema).optional(),
})

export const resourceEndpointsSchema = z.object({
  subsets: z.array(resourceEndpointSpecSubsetsSchema).optional(),
})

export const resourceDeploymentStatusSchema = z.object({
  replicas: z.number(),
  availableReplicas: z.number(),
  readyReplicas: z.number(),
  updatedReplicas: z.number(),
})

export const resourceDeploymentSchema = z.object({
  status: resourceDeploymentStatusSchema,
})

export const datacenterLocationSchema = z.object({
  id: z.string(),
  region: z.string(),
  country: z.string(),
})

export const datacenterSchema = z.object({
  id: z.string(),
  name: z.string(),
  provider: z.string(),
  location: datacenterLocationSchema,
  apiEndpoint: z.string(),
})

export const resourceDaemonSetStatusSchema = z.object({
  numberReady: z.number(),
  numberUnavailable: z.number(),
  currentReplicas: z.number(),
  numberAvailable: z.number(),
  updatedNumberScheduled: z.number(),
  desiredNumberScheduled: z.number(),
  currentNumberScheduled: z.number(),
})

export const resourceDaemonSetSchema = z.object({
  status: resourceDaemonSetStatusSchema,
})

export const resourceConfigurationSpecSchema = z.object({
  type: z.string(),
  b64enc: z.boolean(),
  data: z.string(),
})

export const resourceConfigurationSchema = z.object({
  spec: resourceConfigurationSpecSchema,
})

export const resourceVulnerabilityReportReportVulnerabilitySchema = z.object({
  vulnerabilityID: z.string(),
  severity: z.string(),
  score: z.number(),
  title: z.string(),
  resource: z.string(),
  primaryLink: z.string(),
  installedVersion: z.string(),
  fixedVersion: z.string(),
})

export const resourceVulnerabilityReportReportArtifactSchema = z.object({
  digest: z.string(),
  repository: z.string(),
  tag: z.string(),
})

export const aquaReportScannerSchema = z.object({
  name: z.string(),
  vendor: z.string(),
  version: z.string(),
})

export const aquaReportSummarySchema = z.object({
  criticalCount: z.number(),
  highCount: z.number(),
  lowCount: z.number(),
  mediumCount: z.number(),
  total: z.number().optional(),
})

export const resourceVulnerabilityReportReportSchema = z.object({
  summary: aquaReportSummarySchema,
  scanner: aquaReportScannerSchema,
  artifact: resourceVulnerabilityReportReportArtifactSchema,
  updateTimestamp: z.string(),
  vulnerabilities: z.array(resourceVulnerabilityReportReportVulnerabilitySchema),
})

export const resourceConfigAuditReportSchema = z.object({
  report: resourceVulnerabilityReportReportSchema,
})

export const resourceClusterVulnerabilityReportReportStatusSchema = z.object({
  status: vulnerabilityStatusSchema,
  until: timeSchema.optional(),
  reason: vulnerabilityDismissalReasonSchema.optional(),
  comment: z.string().optional(),
  riskAssessment: z.string().optional(),
})

export const ownerReferenceSchema = z.object({
  apiVersion: z.string(),
  kind: z.string(),
  name: z.string(),
  uid: z.string(),
  controller: z.boolean().optional(),
  blockOwnerDeletion: z.boolean().optional(),
})

export const resourceClusterVulnerabilityReportReportOwnerSchema = z.object({
  digest: z.string(),
  repository: z.string(),
  tag: z.string(),
  resource: z.string(),
  installedVersion: z.string(),
  fixedVersion: z.string(),
  namespace: z.string(),
  ownerReferences: z.array(ownerReferenceSchema),
})

export const resourceClusterVulnerabilityReportSummarySchema = z.object({
  critical: z.number(),
  high: z.number(),
  medium: z.number(),
  low: z.number(),
  unknown: z.number(),
})

export const resourceClusterVulnerabilityReportReportSchema = z.object({
  severity: z.string(),
  score: z.number(),
  title: z.string(),
  primaryLink: z.string(),
  firstObserved: timeSchema,
  lastObserved: timeSchema,
  owners: z.array(resourceClusterVulnerabilityReportReportOwnerSchema),
  status: resourceClusterVulnerabilityReportReportStatusSchema,
})

export const resourceKubernetesClusterOrderStatusConditionSchema = z.object({
  type: z.string(),
  status: z.string(),
  lastTransitionTime: z.string(),
  reason: z.string(),
  message: z.string(),
})

export const resourceClusterOrderStatusSchema = z.object({
  status: z.string(),
  phase: z.string(),
  conditions: z.array(resourceKubernetesClusterOrderStatusConditionSchema),
  createdTime: z.string(),
  updatedTime: z.string(),
  lastObservedTime: z.string(),
})

export const resourceClusterOrderSpecNodePoolSchema = z.object({
  name: z.string(),
  machineClass: z.string(),
  count: z.number(),
})

export const resourceClusterOrderSpecSchema = z.object({
  provider: z.string(),
  clusterName: z.string(),
  projectId: z.string(),
  orderBy: z.string(),
  environment: z.number(),
  criticality: z.number(),
  sensitivity: z.number(),
  highAvailability: z.boolean(),
  nodePools: z.array(resourceClusterOrderSpecNodePoolSchema),
  serviceTags: z.record(z.string(), z.string()).optional(),
  providerConfig: z.record(z.any(), z.any()).optional(),
  ownerGroup: z.string(),
})

export const resourceClusterOrderSchema = z.object({
  spec: resourceClusterOrderSpecSchema,
  status: resourceClusterOrderStatusSchema,
})

export const resourceClusterComplianceReportSchema = z.object({})

export const resourceCertificateStatusConditionSchema = z.object({
  lastTransitionTime: z.string(),
  observedGeneration: z.number(),
  message: z.string(),
  reason: z.string(),
  status: z.string(),
  type: z.string(),
})

export const resourceCertificateStatusSchema = z.object({
  notBefore: z.string(),
  notAfter: z.string(),
  renewalTime: z.string(),
  conditions: z.array(resourceCertificateStatusConditionSchema),
})

export const resourceCertificateSpecIssuerrefSchema = z.object({
  group: z.string(),
  kind: z.string(),
  name: z.string(),
})

export const resourceCertificateSpecSchema = z.object({
  dnsNames: z.array(z.string()),
  secretName: z.string(),
  issuerRef: resourceCertificateSpecIssuerrefSchema,
  usages: z.array(z.string()).optional(),
})

export const resourceCertificateSchema = z.object({
  spec: resourceCertificateSpecSchema,
  status: resourceCertificateStatusSchema,
})

export const resourceIndirectBackupTargetSchema = z.object({
  type: z.string(),
  ids: z.array(z.string()),
  keyValues: z.record(z.string(), z.array(z.string())),
})

export const resourceBackupDestinationSchema = z.object({
  name: z.string(),
  id: z.string(),
  type: z.string(),
  status: z.string(),
})

export const resourceBackupStorageSchema = z.object({
  unit: z.string(),
  sourceSize: z.number(),
  logicalSize: z.number(),
  physicalSize: z.number(),
})

export const resourceBackupRunDestinationSchema = z.object({
  name: z.string(),
  id: z.string(),
  type: z.string(),
  status: z.string(),
  expiryTime: timeSchema,
})

export const resourceBackupSourceSchema = z.object({
  name: z.string(),
  id: z.string(),
  uuid: z.string(),
  type: z.string(),
})

export const resourceBackupTargetSchema = z.object({
  name: z.string(),
  id: z.string(),
  externalId: z.string(),
  source: resourceBackupSourceSchema.optional(),
})

export const resourceBackupRetentionSchema = z.object({
  unit: z.string(),
  duration: z.number(),
})

export const resourceBackupScheduleSchema = z.object({
  startTime: z.string(),
  endTime: z.string(),
  frequency: z.number(),
  unit: z.string(),
  retention: resourceBackupRetentionSchema,
})

export const resourceBackupRunSchema = z.object({
  id: z.string(),
  backupTargets: z.array(resourceBackupTargetSchema),
  backupDestinations: z.array(resourceBackupRunDestinationSchema),
  startTime: timeSchema,
  endTime: timeSchema,
  expiryTime: timeSchema,
  backupStorage: resourceBackupStorageSchema,
})

export const resourceBackupJobStatusSchema = z.object({
  name: z.string(),
  status: z.string(),
  policyId: z.string(),
  schedules: z.array(resourceBackupScheduleSchema),
  activeTargets: z.array(resourceBackupTargetSchema),
  indirectBackupTargets: z.array(resourceIndirectBackupTargetSchema),
  backupDestinations: z.array(resourceBackupDestinationSchema),
  location: z.string(),
  lastUpdated: timeSchema,
  policyName: z.string(),
  runs: z.array(resourceBackupRunSchema),
})

export const resourceBackupJobSpecSchema = z.object({
  name: z.string(),
  status: z.string(),
  policyId: z.string(),
  schedules: z.array(resourceBackupScheduleSchema),
  activeTargets: z.array(resourceBackupTargetSchema),
  indirectBackupTargets: z.array(resourceIndirectBackupTargetSchema),
  backupDestinations: z.array(resourceBackupDestinationSchema),
})

export const resourceApplicationSpecDestinationSchema = z.object({
  name: z.string(),
  namespace: z.string(),
  server: z.string(),
})

export const resourceAppProjectSpecSchema = z.object({
  description: z.string(),
  sourceRepos: z.array(z.string()),
  destinations: z.array(resourceApplicationSpecDestinationSchema),
})

export const resourceApplicationStatusSyncSchema = z.object({
  revision: z.string(),
  status: z.string(),
})

export const resourceApplicationStatusHealthSchema = z.object({
  message: z.string(),
  status: z.string(),
})

export const resourceApplicationStatusOperationstateSchema = z.object({
  startedAt: z.string(),
  finishedAt: z.string(),
  phase: z.string(),
  status: z.string(),
  message: z.string(),
})

export const resourceApplicationStatusSchema = z.object({
  sourceType: z.string(),
  reconciledAt: z.string(),
  operationState: resourceApplicationStatusOperationstateSchema,
  health: resourceApplicationStatusHealthSchema,
  sync: resourceApplicationStatusSyncSchema,
})

export const resourceApplicationSpecSyncpolicyRetryBackoffSchema = z.object({
  duration: z.string(),
  factor: z.number(),
  maxDuration: z.string(),
})

export const resourceApplicationSpecSyncpolicyRetrySchema = z.object({
  backoff: resourceApplicationSpecSyncpolicyRetryBackoffSchema.optional(),
  limit: z.number(),
})

export const resourceApplicationSpecSyncpolicyAutomatedSchema = z.object({
  allowEmpty: z.boolean(),
  prune: z.boolean(),
  selfHeal: z.boolean(),
})

export const resourceApplicationSpecSyncpolicySchema = z.object({
  automated: resourceApplicationSpecSyncpolicyAutomatedSchema.optional(),
  retry: resourceApplicationSpecSyncpolicyRetrySchema.optional(),
  syncOptions: z.array(z.string()),
})

export const resourceApplicationSpecSourceSchema = z.object({
  chart: z.string().optional(),
  path: z.string().optional(),
  repoURL: z.string(),
  targetRevision: z.string(),
})

export const resourceApplicationSpecSchema = z.object({
  destination: resourceApplicationSpecDestinationSchema,
  project: z.string(),
  source: resourceApplicationSpecSourceSchema,
  syncPolicy: resourceApplicationSpecSyncpolicySchema,
})

export const resourceApplicationSchema = z.object({
  spec: resourceApplicationSpecSchema,
  status: resourceApplicationStatusSchema,
})

export const resourceTagSchema = z.object({
  key: z.string(),
  value: z.string(),
  properties: z.record(z.string(), z.string()),
})

export const resourceRorMetaSchema = z.object({
  version: z.string().optional(),
  lastReported: z.string().optional(),
  internal: z.boolean().optional(),
  hash: z.string().optional(),
  ownerref: rorResourceOwnerReferenceSchema.optional(),
  action: z.string().optional(),
  tags: z.array(resourceTagSchema).optional(),
})

export const fieldsV1Schema = z.object({})

export const managedFieldsEntrySchema = z.object({
  manager: z.string().optional(),
  operation: z.string().optional(),
  apiVersion: z.string().optional(),
  time: timeSchema.optional(),
  fieldsType: z.string().optional(),
  fieldsV1: fieldsV1Schema.optional(),
  subresource: z.string().optional(),
})

export const objectMetaSchema = z.object({
  name: z.string().optional(),
  generateName: z.string().optional(),
  namespace: z.string().optional(),
  selfLink: z.string().optional(),
  uid: z.string().optional(),
  resourceVersion: z.string().optional(),
  generation: z.number().optional(),
  creationTimestamp: timeSchema.optional(),
  deletionTimestamp: timeSchema.optional(),
  deletionGracePeriodSeconds: z.number().optional(),
  labels: z.record(z.string(), z.string()).optional(),
  annotations: z.record(z.string(), z.string()).optional(),
  ownerReferences: z.array(ownerReferenceSchema).optional(),
  finalizers: z.array(z.string()).optional(),
  managedFields: z.array(managedFieldsEntrySchema).optional(),
})

export const resourceAppProjectSchema = z.object({
  spec: resourceAppProjectSpecSchema,
})

export const resourceBackupJobSchema = z.object({
  id: z.string(),
  provider: z.string(),
  source: z.string(),
  status: resourceBackupJobStatusSchema,
  spec: resourceBackupJobSpecSchema,
})

export const resourceClusterVulnerabilityReportSchema = z.object({
  summary: resourceClusterVulnerabilityReportSummarySchema,
  report: z.record(z.string(), resourceClusterVulnerabilityReportReportSchema),
})

export const resourceDatacenterSchema = z.object({
  spec: resourceDaemonSetStatusSchema,
  legacy: datacenterSchema,
})

export const resourceExposedSecretReportSchema = z.object({
  report: resourceVulnerabilityReportReportSchema,
})

export const resourceKubernetesClusterSchema = z.object({
  spec: kubernetesClusterSpecSchema,
  status: kubernetesClusterStatusSchema.optional(),
})

export const resourceNetworkPolicySchema = z.object({
  spec: resourceNetworkPolicySpecSchema,
  status: resourceNetworkPolicyStatusSchema,
})

export const resourceRbacAssessmentReportSchema = z.object({
  report: resourceVulnerabilityReportReportSchema,
})

export const resourceServiceSchema = z.object({
  spec: resourceServiceSpecSchema,
})

export const resourceVirtualMachineSchema = z.object({
  externalId: z.string(),
  spec: resourceVirtualMachineSpecSchema,
  status: resourceVirtualMachineStatusSchema,
  provider: z.string(),
})

export const resourceVulnerabilityEventSchema = z.object({
  spec: resourceVulnerabilityEventSpecSchema,
})

export const resourceVulnerabilityReportSchema = z.object({
  report: resourceVulnerabilityReportReportSchema,
})

export const resourceQueryFilterSchema = z.object({
  field: z.string().optional(),
  value: z.string().optional(),
  type: z.string().optional(),
  operator: z.string().optional(),
})

export const resourceQueryOrderSchema = z.object({
  field: z.string().optional(),
  descending: z.boolean().optional(),
  index: z.number().optional(),
})

export const groupVersionKindSchema = z.object({
  Group: z.string(),
  Version: z.string(),
  Kind: z.string(),
})

export const resourceQuerySchema: z.ZodSchema<ResourceQuery> = z.lazy(() =>
  z.object({
    versionkind: groupVersionKindSchema.optional(),
    uids: z.array(z.string()).optional(),
    ownerrefs: z.array(rorResourceOwnerReferenceSchema).optional(),
    fields: z.array(z.string()).optional(),
    order: z.array(resourceQueryOrderSchema).optional(),
    filters: z.array(resourceQueryFilterSchema).optional(),
    offset: z.number().optional(),
    limit: z.number().optional(),
    relatedresources: z.array(resourceQuerySchema).optional(),
  })
)

export const resourceIngressSpecRulesHttpPathsSchema = z.object({
  backend: resourceIngressSpecRulesHttpPathsBackendSchema,
  path: z.string(),
  pathType: z.string(),
})

export const resourceIngressSpecRulesHttpSchema = z.object({
  paths: z.array(resourceIngressSpecRulesHttpPathsSchema),
})

export const resourceIngressSpecRulesSchema = z.object({
  apiGroup: z.string(),
  http: resourceIngressSpecRulesHttpSchema,
})

export const resourceIngressSpecSchema = z.object({
  defaultBackend: resourceIngressSpecRulesHttpPathsBackendSchema.optional(),
  ingressClassName: z.string(),
  rules: z.array(resourceIngressSpecRulesSchema),
  tls: z.array(resourceIngressSpecTlsSchema),
})

export const resourceIngressSchema = z.object({
  spec: resourceIngressSpecSchema,
  status: resourceIngressStatusSchema,
})

export const resourceSchema = z.object({
  kind: z.string().optional(),
  apiVersion: z.string().optional(),
  metadata: objectMetaSchema.optional(),
  rormeta: resourceRorMetaSchema,
  application: resourceApplicationSchema.optional(),
  appproject: resourceAppProjectSchema.optional(),
  backupjob: resourceBackupJobSchema.optional(),
  certificate: resourceCertificateSchema.optional(),
  clustercompliancereport: resourceClusterComplianceReportSchema.optional(),
  clusterorder: resourceClusterOrderSchema.optional(),
  clustervulnerabilityreport: resourceClusterVulnerabilityReportSchema.optional(),
  configauditreport: resourceConfigAuditReportSchema.optional(),
  configuration: resourceConfigurationSchema.optional(),
  daemonset: resourceDaemonSetSchema.optional(),
  datacenter: resourceDatacenterSchema.optional(),
  deployment: resourceDeploymentSchema.optional(),
  endpoints: resourceEndpointsSchema.optional(),
  exposedsecretreport: resourceExposedSecretReportSchema.optional(),
  ingressclass: resourceIngressClassSchema.optional(),
  ingress: resourceIngressSchema.optional(),
  kubernetescluster: resourceKubernetesClusterSchema.optional(),
  namespace: resourceNamespaceSchema.optional(),
  networkpolicy: resourceNetworkPolicySchema.optional(),
  node: resourceNodeSchema.optional(),
  persistentvolumeclaim: resourcePersistentVolumeClaimSchema.optional(),
  pod: resourcePodSchema.optional(),
  policyreport: resourcePolicyReportSchema.optional(),
  project: resourceProjectSchema.optional(),
  rbacassessmentreport: resourceRbacAssessmentReportSchema.optional(),
  replicaset: resourceReplicaSetSchema.optional(),
  route: resourceRouteSchema.optional(),
  service: resourceServiceSchema.optional(),
  slackmessage: resourceSlackMessageSchema.optional(),
  statefulset: resourceStatefulSetSchema.optional(),
  storageclass: resourceStorageClassSchema.optional(),
  tanzukubernetescluster: resourceTanzuKubernetesClusterSchema.optional(),
  tanzukubernetesrelease: resourceTanzuKubernetesReleaseSchema.optional(),
  virtualmachineclass: resourceVirtualMachineClassSchema.optional(),
  virtualmachine: resourceVirtualMachineSchema.optional(),
  vulnerabilityevent: resourceVulnerabilityEventSchema.optional(),
  vulnerabilityreport: resourceVulnerabilityReportSchema.optional(),
})

export const resourceSetSchema = z.object({
  resources: z.array(resourceSchema).optional(),
})
