import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { AppShell } from '@/components/app-shell/app-shell'
import { Providers } from './providers'
import { getDarkModePreferenceAction } from '@/utils/dark-mode.actions'

const inter = Inter({ subsets: ['latin'], variable: '--font-family-sans' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  // Retrieve the user's preferred color scheme
  // otherwise it defaults to "system"
  const theme = await getDarkModePreferenceAction()

  return (
    <html lang='en' className={inter.variable} data-color-scheme={theme}>
      <body>
        <Providers>
          <AppShell>{children}</AppShell>
        </Providers>
      </body>
    </html>
  )
}
