import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "./globals.css";
import { AppShell } from "@/components/app-shell/app-shell";

const inter = Inter({ subsets: ['latin'], variable: "--font-family-sans" })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"className={inter.variable}>
      <body>
        <AppShell>
          {children}
        </AppShell>
      </body>
    </html>
  );
}
