// import type { Layouts } from 'react-grid-layout'

// export const standardLayouts: Layouts = {
//   lg: [
//     { i: 'cpu', x: 0, y: 0, w: 14, h: 14, minW: 14, minH: 14 },
//     // { i: 'memory', x: 6, y: 30, w: 6, h: 4, minW: 4, minH: 4 },
//     // { i: 'configuration', x: 12, y: 30, w: 6, h: 4, minW: 4, minH: 5 },
//     // { i: 'team', x: 0, y: 34, w: 6, h: 5, minW: 4, minH: 5 },
//     // { i: 'ad-groups', x: 6, y: 34, w: 6, h: 5, minW: 4, minH: 5 },
//     // { i: 'service-id', x: 12, y: 4, w: 6, h: 5, minW: 4, minH: 5 },
//     // { i: 'info', x: 0, y: 8, w: 12, h: 8, minW: 9, minH: 8 },
//     // { i: 'networks', x: 0, y: 14, w: 12, h: 16, minW: 9, minH: 16 },
//     //{ i: 'control-panel', x: 18, y: 0, w: 6, h: 9, minW: 6, minH: 9 },
//   ],
//   md: [
//     { i: 'cpu', x: 0, y: 0, w: 14, h: 14, minW: 14, minH: 14 },
//     // { i: 'memory', x: 6, y: 30, w: 6, h: 4, minW: 4, minH: 4 },
//     // { i: 'configuration', x: 12, y: 30, w: 6, h: 4, minW: 4, minH: 5 },
//     // { i: 'team', x: 0, y: 34, w: 6, h: 5, minW: 4, minH: 5 },
//     // { i: 'ad-groups', x: 6, y: 34, w: 6, h: 5, minW: 4, minH: 5 },
//     // { i: 'service-id', x: 12, y: 4, w: 6, h: 5, minW: 4, minH: 5 },
//     // { i: 'info', x: 0, y: 8, w: 12, h: 8, minW: 6, minH: 8 },
//     // { i: 'networks', x: 0, y: 20, w: 12, h: 16, minW: 9, minH: 16 },
//     //{ i: 'control-panel', x: 20, y: 0, w: 6, h: 9, minW: 6, minH: 9 },
//   ],
//   sm: [
//     { i: 'cpu', x: 0, y: 0, w: 14, h: 14, minW: 14, minH: 14 },
//     // { i: 'memory', x: 4, y: 30, w: 4, h: 4, minW: 4, minH: 4 },
//     // { i: 'configuration', x: 8, y: 30, w: 4, h: 4, minW: 4, minH: 5 },
//     // { i: 'team', x: 0, y: 34, w: 4, h: 5, minW: 4, minH: 5 },
//     // { i: 'ad-groups', x: 4, y: 34, w: 4, h: 5, minW: 4, minH: 5 },
//     // { i: 'service-id', x: 8, y: 4, w: 4, h: 5, minW: 4, minH: 5 },
//     // { i: 'info', x: 0, y: 8, w: 12, h: 8, minW: 9, minH: 8 },
//     //{ i: 'networks', x: 0, y: 12, w: 12, h: 16, minW: 9, minH: 16 },
//     // { i: 'control-panel', x: 0, y: 28, w: 6, h: 9, minW: 6, minH: 9 },
//   ],
//   xs: [
//     { i: 'cpu', x: 0, y: 0, w: 14, h: 14, minW: 14, minH: 14 },
//     // { i: 'memory', x: 2, y: 30, w: 2, h: 4, minW: 2, minH: 4 },
//     // { i: 'configuration', x: 4, y: 30, w: 2, h: 4, minW: 2, minH: 5 },
//     // { i: 'team', x: 0, y: 34, w: 2, h: 5, minW: 4, minH: 5 },
//     // { i: 'ad-groups', x: 2, y: 34, w: 2, h: 5, minW: 4, minH: 5 },
//     // { i: 'service-id', x: 4, y: 4, w: 2, h: 5, minW: 4, minH: 5 },
//     // { i: 'info', x: 0, y: 8, w: 6, h: 8, minW: 4, minH: 8 },
//     // { i: 'networks', x: 0, y: 12, w: 6, h: 16, minW: 4, minH: 16 },
//     // { i: 'control-panel', x: 0, y: 28, w: 6, h: 9, minW: 6, minH: 9 },
//   ],
// }
